// lib/config.ts
export const configs = [
  {
    id: 'energy',
    name: 'Energy Portfolio',
    initialCash: 14000,
    initialMargin: 6000,
    initialValue: 20000,
    cashRatio: 0.7,
    marginRatio: 0.3,
    stopLossValue: 14000,
    takeProfitValue: 30000,
    enableDRIP: true,
    stocks: [
      { symbol: 'CNQ', name: 'Canadian Natural', cashAllocation: 4998.44, useMargin: true },
      { symbol: 'SU', name: 'Suncor', cashAllocation: 5049.22, useMargin: true },
      { symbol: 'TRMKF', name: 'Tourmaline', cashAllocation: 4106.85, useMargin: true },
      { symbol: 'AETUF', name: 'ARC Resources', cashAllocation: 3010, useMargin: true },
      { symbol: 'TRP', name: 'TC Energy', cashAllocation: 3020.66, useMargin: true },
    ],
    commodities: [
      { symbol: 'CL=F', name: 'WTI Crude Oil', unit: 'per bbl' },
      { symbol: 'NG=F', name: 'Henry Hub Natural Gas', unit: 'per MMBtu' },
    ],
  },
  {
    id: 'copper',
    name: 'Copper Portfolio',
    initialCash: 6000,
    initialMargin: 3857,
    initialValue: 9857,
    cashRatio: 0.7,
    marginRatio: 0.3,
    stopLossValue: 7000,
    takeProfitValue: 15000,
    enableDRIP: true,
    stocks: [
      { symbol: 'FCX', name: 'Freeport-McMoRan', cashAllocation: 2069.58, useMargin: true },
      { symbol: 'COPX', name: 'Global X Copper Miners ETF', cashAllocation: 1308.5, useMargin: true },
      { symbol: 'ERO', name: 'Ero Copper', cashAllocation: 783.65, useMargin: true },
      { symbol: 'HBM', name: 'Hudbay Minerals', cashAllocation: 756.45, useMargin: true },
    ],
    commodities: [ { symbol: 'HG=F', name: 'Copper', unit: 'per lb' } ],
  },
] as const;