// lib/config.ts
export const configs = [
  {
    id: 'energy',
    name: 'Energy Portfolio',
    initialCash: 14000,
    initialMargin: 6000,
    initialValue: 20000,
    cashRatio: 0.7,
    marginRatio: 0.3,
    stopLossValue: 14000,
    takeProfitValue: 30000,
    enableDRIP: true,
    stocks: [
      { symbol: 'CNQ', name: 'Canadian Natural', cashAllocation: 3500, useMargin: true },
      { symbol: 'SU', name: 'Suncor', cashAllocation: 3500, useMargin: true },
      { symbol: 'TRMLF', name: 'Tourmaline', cashAllocation: 2800, useMargin: true },
      { symbol: 'AETUF', name: 'ARC Resources', cashAllocation: 2100, useMargin: true },
      { symbol: 'TRP', name: 'TC Energy', cashAllocation: 2100, useMargin: true },
    ],
    commodities: [
      { symbol: 'CL=F', name: 'WTI Crude Oil', unit: 'per bbl' },
      { symbol: 'NG=F', name: 'Henry Hub Natural Gas', unit: 'per MMBtu' },
    ],
  },
  {
    id: 'copper',
    name: 'Copper Portfolio',
    initialCash: 7000,
    initialMargin: 3000,
    initialValue: 10000,
    cashRatio: 0.7,
    marginRatio: 0.3,
    stopLossValue: 7000,
    takeProfitValue: 15000,
    enableDRIP: true,
    stocks: [
      { symbol: 'FCX', name: 'Freeport-McMoRan', cashAllocation: 2800, useMargin: true },
      { symbol: 'COPX', name: 'Global X Copper Miners ETF', cashAllocation: 2100, useMargin: true },
      { symbol: 'ERO', name: 'Ero Copper', cashAllocation: 1050, useMargin: true },
      { symbol: 'HBM', name: 'Hudbay Minerals', cashAllocation: 1050, useMargin: true },
    ],
    commodities: [ { symbol: 'HG=F', name: 'Copper', unit: 'per lb' } ],
  },
] as const;